version: '3'

services:
  bot:
    build: .
    container_name: telegram-video-bot
    volumes:
      - ./src:/app/src
      - ./src/resources:/app/src/resources
    env_file:
      - .env
    restart: always 